# ls
alias ls='ls --color=auto'
alias l='ls -1'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lrt='ls -rtl'

# grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# file cp/mv/rm
alias mv='mv -vi'
alias rm='rm -vi'
alias cp='cp -vi'
alias ..='cd ..'

# move to dirs
alias gh="cd $HOME/Dev/Github"
alias vs="cd $HOME/Dev/VisualStudio"
alias bb="cd $HOME/Dev/Bitbucket"
alias gl="cd $HOME/Dev/Gitlab"

# git
alias git_unpushed='git log origin/master..HEAD'
alias git_diff_unpushed='git diff origin/master..HEAD'


# misc
alias dus='du -sm * | sort -n'
alias filezilla='filezilla -a="$(pwd)"'
alias video_find="find -name '*mp4' -o -name '*mkv' -o -name '*avi' | sort"

# smv script aliases
for h in $(grep '^Host' ~/.ssh/config  | sed 's/^Host [ ]*\(.*\)[ ]*/\1/')
do
  alias $h="ssh $h"
  alias $h-smv="smv.sh -h $h"
done

# rclone_mv aliases
alias hubic_mv='rclone_mv.sh hubic default/Media'
alias remote_mv_from_hubic='rclone_mv_from_remote.sh hubic default/Media'

# dev aliases
alias mk='make -j 2'

# python3 as default
alias python='python3'
